TILE_SIZE = 16
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

COLUMNS = 8
ROWS = 4
CELL_SIZE = 5

TILE_WIDTH = 32
TILE_HEIGHT = 32

# TILE_WIDTH = SCREEN_WIDTH/(CELL_X*CELL_SIZE)
# TILE_HEIGHT = SCREEN_HEIGHT/(CELL_Y*CELL_SIZE)
# colors
BG_COLOR = '#a66133'
PLAYER_COLOR = '#C4F7FF'
TILE_COLOR = '#612903'